name: Deploy Pharmacy App - Console

on: 
  push:
    branches: 
      - main
      
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 18 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: Install NPM Modules (use yarn)
      run: yarn install --frozen-lockfile

    - name: Build Project
      run: npm run build
    
    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.HOST }}
        port: 22
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        scp_source: ./dist/app/
        scp_target: /home/pharmacy/public_html/console/
        before_script: |
          rm -rf ./console/*
        after_script: |
          mv -v /home/pharmacy/public_html/console/app/* /home/pharmacy/public_html/console
          rm -rf /home/pharmacy/public_html/console/app/